services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data # comment it if you have problems with permissions, but than you won't stash your db data
      - ./etc/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    depends_on: 
      db:
        condition: service_healthy
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_URLS: "http://+:5000/"
      ConnectionStrings__Horizons: "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=password"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
      - "5000:5000"
      - "5001:5001"
    image: profileanalytics-backend

